狸河電鉄TIMSのTASC表示対応
Kesigomon/bve-traincrew-bridge pull request #1
Opened 2023-11-19 06:38 UTC by haruyukitanuki

2023-11-19 09:29 UTC, Kesigomon requested changes
PRありがとうございます！

以下の修正をお願いします。
- 設定ファイルでREST APIのオンオフ、ホストポートが変更できるようにする
- TASCパネルもオンオフ可能にする？
  - TASCではない BVEプラグインも動かせるようにしたいため。(なにか良い方法があるような気がします)

2023-11-19 09:29 UTC, Kesigomon commented
今Bve-autopilotのものを書いてますけど、ゆくゆくは大半のBVEプラグインを動かせる土台を作って
プラグイン向けにカスタムできるようにしたいですね

2023-11-19 10:10 UTC, haruyukitanuki commented
> 設定ファイルでREST APIのオンオフ、ホストポートが変更できるようにする
実装の問題ありませんが、タヌ電TIMSの改造APIポートは56000～56005です。

> TASCパネルもオンオフ可能にする？
タヌ電TIMS側ですか？タヌ電TIMSにTASC情報が送信しないことなら、「TASC電源」の表示灯が点けられないです。

> プラグイン向けにカスタムできるようにしたいですね
REST APIの方は難しいです。今はタヌ電の改造APIフォーマットで送信することですが、ちょっとわからんが、もっと詳しく説明して欲しいです。

2023-11-19 14:15 UTC, Kesigomon commented
> タヌ電TIMSの改造APIポートは56000～56005です。
ここはタヌ電側でもポート変更できるようにすると良さそうですね
> タヌ電TIMSにTASC情報が送信しないことなら、「TASC電源」の表示灯が点けられないです。
TASCの情報が送信されてないなら、TASC電源をオフにするか、あるいはTASC故障とつけるとか、はたまたあるいはTASCパネル表示しないとか・・・

> もっと詳しく説明して欲しいです。
今はBve-autopilot向けのカスタムを実装していますが、BVEプラグインはBve-autopilot以外にもあります。
bve-autopilot以外のプラグインもTraincrew上で動かせるように、共通化できるところは共通化していきたいです。例えば移動距離とか速度とかは他のBVEプラグインでも同じで良いはずです。

しかし共通化できなかったり、何線ごっこ向けのカスタムしたいところもあります。例えば以下。
- プラグインによって地上子の番号や仕様が違う（コレは共通化できないもの）
  - 番号とか信号の仕様が全部違うはず（送るという点では共通だけど）
- どのタイミングで地上子の情報を送るか（これは〇〇線ごっこに近いもの）
  - 例えばTASC向けの地上子は駅の近くにしかないので、初期減速は運転士がやらないといけない
  - それよりももっと手前にあって、運転士が何も操作しなくても止まれる

なので、共通化できるところは共通化して、開発者が自由にカスタムできるようなソフトウェアを目指してます。

2023-11-19 16:07 UTC, haruyukitanuki commented
改造APIポートは56000～56005は固定です。なぜかと言うと、タヌ電TIMSのデータを改造できるアプリは、最大5つまで可能です。ユーザーのため、使いやすさを考えると、TIMSを改造したいアプリは、このポート間（Port Range）に使用しようと思う。例えばMinecraftの25565みたいです。

---

今はTASCパネルは：
- TIMS起動の時、最初からTASCデータがないとか、または改造アプリ（bve-traincrew-bridge）を見つからないとか、全部のTASCパネルのランプを点けない（消灯の状態）。
- TIMS起動の時、最初からTASCデータがあったら、「TASC電源」を点ける。
- 急にデータがなくなちゃった状態で、「TASC故障」のランプが点ける。

タヌ電TIMS側のTASCパネルは、将来的にオンオフ設定を実装する予定です。または、たぶん改造APIでパネルのオンオフもできる機能（予定ない、でもこんなAPI機能はいいと思う。）

---

REST APIの側について僕の日本語で説明する事は足りませんので、英語にします。すみませんが自動翻訳を利用してください。

From what I am understanding, bve-traincrew-bridge is meant to support other BVE plugins as well which was why it was requested to make the REST API output more versatile and adaptable (please correct me if I'm misunderstanding).

In order to implement this, it should be understood that it would be a very difficult task as there is no such thing as a standard modding API interface for train simulator plugins or things alike. Hence Tanuden TIMS has its own modding interface. 

Example:
```js
{
    runNumber: null,
    currentTime: null,
    nextStation: {
        name: null,
        isStopping: null,
        index: 0,
        distance: null,
    },
    trainState: {
        consist: 0,
        speed: 0,
        speedLimit: 0,
        nextSpeedLimit: {
            limit: null,
            type: null,
            distance: null,
        },
        mrPressure: 0,
        carState: [],
        lamps: {},
    },
    atsState: {
        speed: 0,
        class: null,
        state: null
    },
    controllerState: {
        notch: 0,
        reverser: 0,
    },
    diagram: {
        direction: null,
        boundFor: null,
        serviceType: null,
        stations: []
    }
}
```

As a matter of fact, if you put this into the REST API (with correct values of course), it will override or add values to the Tanuden TIMS data before it reaches the frontend. (The data modding part is done on the tanuden-tims-nativeclient.exe).

If you are okay with this, then sure, we can put this into the REST API code and call it a day.

If let's say we need to modify the Tanuden TIMS UI, then that is where the messy and hellish part will come. I didn't really code Tanuden TIMS with modding in mind from the start, so it is extremely difficult to code this to a level I can accept as good quality code.

On top of that, I'm not sure what other things can BVE plugins modify or require from Tanuden TIMS, other than UI modifications...

2023-11-20 00:35 UTC, haruyukitanuki commented
![image](https://github.com/Kesigomon/bve-traincrew-bridge/assets/119217207/64fa51a3-0989-45e9-9e3f-184a3685ecfd)

2023-11-20 00:37 UTC, haruyukitanuki commented
![image](https://github.com/Kesigomon/bve-traincrew-bridge/assets/119217207/01e26c8b-2f57-4ca6-829e-dadf4af1ddd3)

2023-11-20 13:46 UTC, Kesigomon commented
> If you are okay with this, then sure, we can put this into the REST API code and call it a day.
OK, can you put this?

In addition to that, this bridge should allow users to enable/disable the REST API for Tanuden.

2023-11-20 14:01 UTC, Dylankjy commented
I will implement the function to enable and disable the Tanuden API.

We have one issue about the REST API though. If we're to put the entire example in as of right now without the bridge doing any data manipulation, then the data from train crew is fetched and then it overwrites the Tanuden data redundantly and may cause performance issues.

Perhaps maybe in future when we try it with other BVE plugins, then we could adapt it later on because I don't think we need to send any additional variables other than lamp information.

The burden is on the fact that Tanuden TIMS isn't very flexible at the moment... 😔

2023-11-20 14:02 UTC, haruyukitanuki commented
I will implement the function to enable and disable the Tanuden API.

We have one issue about the REST API though. If we're to put the entire example in as of right now without the bridge doing any data manipulation, then the data from train crew is fetched and then it overwrites the Tanuden data redundantly and may cause performance issues.

Perhaps maybe in future when we try it with other BVE plugins, then we could adapt it later on because I don't think we need to send any additional variables other than lamp information.

The burden is on the fact that Tanuden TIMS isn't very flexible at the moment... 😔

2023-11-20 15:02 UTC, Kesigomon commented on bve-traincrew-bridge/Program.cs
> +        TascData.Power = panelLamps[50] != 0;
ここIndex固定なのが微妙に気になる
プラグインによっては設定できないのもあるので

2023-11-20 15:33 UTC, haruyukitanuki commented on bve-traincrew-bridge/Program.cs
> +        TascData.Power = panelLamps[50] != 0;
んんんー設定ファイルで設定できるのはどうですか？

2023-11-20 15:34 UTC, Kesigomon commented on bve-traincrew-bridge/Program.cs
> +        TascData.Power = panelLamps[50] != 0;
良いです

2023-11-28 17:56 UTC, Kesigomon commented
Todo: 
1: git resetしてもらう
2: タヌ電の機能だけ分離しておく(Program.csには最低限しか書かない)

2023-11-29 02:25 UTC, Kesigomon requested changes
ご確認よろしくお願いします！

2023-11-29 02:25 UTC, Kesigomon commented on bve-traincrew-bridge/LoadConfig.cs
> +            Console.WriteLine("設定ファイルが見つけません。デフォルト設定で起動します。");
```suggestion
            Console.WriteLine("設定ファイルが見つかりませんでした。デフォルト設定で起動します。");
```

2023-11-29 02:25 UTC, Kesigomon commented on bve-traincrew-bridge/Program.cs
> +    private static string TanudenPluginUid = "kesigomon.bve_traincrew_bridge";
タヌ電関連の処理がこのクラスにあると、このクラスの責務が大きくなりすぎなので、別なクラスにすると良いと思います（バージョンはそのままでも良いかも）

2023-11-29 02:25 UTC, Kesigomon commented on bve-traincrew-bridge/Program.cs
> +        if (Config.ApiEnable)
パネルだけ引数で渡してしまって、別クラスにまとめられる気がする

2023-11-29 13:16 UTC, Kesigomon approved these changes
LGTM！
こちらでマージします

2023-11-29 13:16 UTC, merged